- bower.json
It seems to be required for the link line 14 in [iron-dropdown.html](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html):
```html
<link rel="import" href="../iron-behaviors/iron-control-state.html">
```
> Add polymerelements/iron-behaviors

- iron-dropdown-scroll-manager.html
Scroll locking was broken in ShadowDOM, because the result of calling
`element.contains` is different compared to ShadeyDOM (which lacks
encapsulation). What we want in the scroll manager is to query the
composed ShadowDOM tree when testing element hierarchy. So, a new method
and supporting caching mechanism has been added to enable this in a
(hopefully) performant manner.
/cc @notwaldorf
> Fix scroll locking in ShadowDOM

- bower.json
- iron-dropdown-scroll-manager.html
- iron-dropdown.html
- test/iron-dropdown.html
I'm sorry this PR is so giant. I was just trying to get the tests to pass :(
- fixed the docs for the `horizontal` and `vertical` offsets, which I believe were misleading
- fixed the `offset` tests, which weren't actually running (because `done` wasn't defined)
- added more offset tests, to cover all the possible cases 
- added a null check that was triggered by the `allow-outside-scroll` test (which also wasn't running because the attribute was on the wrong element, and `done` wasn't defined)
- the `bower.json` change fixes https://github.com/PolymerElements/iron-dropdown/issues/38
> fix tests, docs, and a null check

- iron-dropdown.html
- test/iron-dropdown.html
Override `_applyFocus` for setting the focus.
Cleanup tests to use `iron-overlay-opened` event instead of timeouts.
Depends on https://github.com/PolymerElements/iron-overlay-behavior/commit/43f0ca38607846417c972cfc232253ce8637be3e (require new release of `iron-overlay-behavior`)
Fixes #57
> override _applyFocus. Use iron-overlay-opened in tests

- test/iron-dropdown.html
Fixes test by using `iron-overlay-opened` event instead of timeouts
> use runAfterOpen instead of timeout

- iron-dropdown.html
- test/iron-dropdown.html
Fixes #59 by checking if dropdown is already opened before reading the values.
Based on PR https://github.com/PolymerElements/iron-dropdown/pull/60 (so tests don't fail)
> read scrollTop/scrollLeft only if opened

- iron-dropdown-scroll-manager.html
- test/iron-dropdown-scroll-manager.html
- test/x-scrollable-element.html
Scroll locking was broken in ShadowDOM because `event.path` does not
contain sufficient information when `currentTarget` is `window`.
Listeners are now being added to `document` instead.
> Fixes scroll lock detection in ShadowDOM

- iron-dropdown-scroll-manager.html
Technically a `rootTarget` could be any EventTarget, not just an element. But here I think we can be confident that it's an element.
> Explain the scrolled target's type to the compiler

- iron-dropdown.html
- test/iron-dropdown.html
Fixes #66, fixes #67, fixes #69 
- `resetFit` will position properly the dropdown (it takes into account parent's stacking contexts)
- `refit` is the responsible of keeping track of the scroll position (not `_onIronResize`) - now scroll position is kept also when calling `refit()`
- cleanup/removal of private methods not needed anymore
- invoke `_finishRenderOpened/_finishRenderClosed`!! Now `iron-overlay-opened/closed` is properly fired :tada:
- handle opening of backdropElement in `_renderOpened/_renderClosed` (if anyone ever used it); now the backdrop animation fires together with the dropdown animation
- limited number of relayouts (e.g. memoize `_isRTL` on `attached`)
> override center, handle parent's stacking context

- iron-dropdown.html
The need for this was fixed in [web-animations-js 2.2.0](https://github.com/web-animations/web-animations-js/releases/tag/2.2.0)
> Remove opaque-animation

- iron-dropdown.html
Needs https://github.com/PolymerElements/iron-fit-behavior/pull/49 to be merged and released.
Remove `refit` override which was basically preserving the scroll position. This is now done by the `iron-fit-behavior`
> remove refit override

- iron-dropdown.html
Ensure we unlock the element when it gets detached.
Directly call `_finishRenderOpened/Closed` instead of invoking the ones from `IronOverlayBehaviorImpl`.
No need to `open/close` the backdrop as it's already done by `iron-overlay-behavior`.
Cleanup of `_updateAnimationConfig`
> unlock on detach. Cleanup _updateAnimationConfig

- iron-dropdown-scroll-manager.html
- iron-dropdown.html
- test/iron-dropdown-scroll-manager.html
- test/iron-dropdown.html
- test/x-scrollable-element.html
Fixes #54 , fixes #43.
For #54, the goal is to keep the overflow on `document.body`, and prevent the scrolling from happening if:
- the scroll happens outside the locked element
- the scroll happens inside the locked element, but the target is contained in scrollable parents that cannot scroll (because they're at their boundaries already)
For #43, the `scroll` event listener on document will restore scrolling if it happens because of a user text selection or if the user scrolls through the side scroll bars. If `allowScrollOutside`, it will call `refit`
> keep overflow, calculate scroll size

- iron-dropdown-scroll-manager.html
- iron-dropdown.html
- test/iron-dropdown-scroll-manager.html
- test/iron-dropdown.html
- test/x-scrollable-element.html
Reverts PolymerElements/iron-dropdown#64 as it removed a public method, which is a breaking change that needs to be first investigated.
> Revert "keep overflow, calculate scroll size"

- iron-dropdown-scroll-manager.html
- iron-dropdown.html
- test/iron-dropdown-scroll-manager.html
- test/iron-dropdown.html
- test/x-scrollable-element.html
(started in https://github.com/PolymerElements/iron-dropdown/pull/64, which was reverted because it introduced a breaking change)
Fixes #54 , fixes #43.
For #54, the goal is to keep the overflow on `document.body`, and prevent the scrolling from happening if:
- the scroll happens outside the locked element
- the scroll happens inside the locked element, but the target is contained in scrollable parents that cannot scroll (because they're at their boundaries already)
For #43, the `scroll` event listener on document will restore scrolling if it happens because of a user text selection or if the user scrolls through the side scroll bars. If `allowScrollOutside`, it will call `refit`.
I've profiled the performance of the change using this file …
> keep overflow, prevent events that cause scrolling

- bower.json
- iron-dropdown-scroll-manager.html
- test/iron-dropdown-scroll-manager.html
Fixes https://github.com/PolymerElements/paper-dropdown-menu/issues/187, fixes https://github.com/PolymerElements/iron-dropdown/issues/96
Calling `event.preventDefault()` on `keydown` events can break a11y. 
`iron-dropdown-scroll-manager` needed to prevent in order to avoid any scroll from happening, but since `iron-dropdown` is capable of [restoring the scroll position](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown.html#L260), the `keydown` event listener is not really needed. We gain a11y in exchange of a reflow...
> remove keydown listener

- bower.json
- iron-dropdown.html
Fixes tests. This should have been done in PR https://github.com/PolymerElements/iron-dropdown/pull/93. Tests were passing because of an earlier version of `iron-overlay-behavior` which was setting `opened = false` on detached. This has been fixed in v1.8.6 https://github.com/PolymerElements/iron-overlay-behavior/pull/183.
Ah, dependencies..
> remove listener on detached

- iron-dropdown.html
- test/iron-dropdown.html
Now `sizingTarget` is configured in `attached` instead of `_openedChanged`. Also added some tests.
@valdrinkoshi PTAL.
> configure sizingTarget on attached, fixes #102

- iron-dropdown-scroll-manager.html
- iron-dropdown.html
- test/iron-dropdown.html
Fixes #118 by defaulting to `this` if no `contentElement` is available.
Also, lower-cased variables since they're not constants.
> Default to host when contentElement not available

- iron-dropdown-scroll-manager.html
Ensure the event listeners are added with `useCapture = true` and `passive = false`. This is important especially for `touchstart` event listeners; chrome 57 will default `passive = true` if not otherwise specified.
Fixes tests currently failing on master https://travis-ci.org/PolymerElements/iron-dropdown/builds/184680907
> Ensure useCapture=true on M57

- .gitignore
- .travis.yml
- README.md
- bower.json
- demo/index.html
- demo/web-animations.html
- demo/x-select.html
- iron-dropdown-scroll-manager.html
- iron-dropdown.html
- test/index.html
- test/iron-dropdown-scroll-manager.html
- test/iron-dropdown.html
Relevant updates:
- use `demo-snippet` on demo page, add dev-dependency on `web-animations-js` as `neon-animation` doesn't anymore
- make events `composed` in the unit tests
- removed deprecated private property `_focusTarget`
- explicitly set scroll listeners to be `passive: false` as in Canary `touchstart, touchmove` listeners treat the target as passive by default https://bugs.chromium.org/p/chromium/issues/detail?id=652519
> 2.0 preview

- .travis.yml
- demo/grow-height-animation.html
- demo/x-select.html
- iron-dropdown-scroll-manager.html
- iron-dropdown.d.ts
- iron-dropdown.html
- package-lock.json
- package.json
- test/index.html
- test/iron-dropdown.html
- test/x-scrollable-element.html
Runs the experimental autoformatter [webmat](https://github.com/PolymerLabs/webmat) which runs clang-format on js files and makes it so that it can run on HTML files. Please look through this PR with `?w=1` in the diff to make sure that no logic was changed.
What has changed?
You can run the formatter on the whole project by running `npm run format` and ex/include files from the formatter, and enter your custom clang-format config in a formatconfig.json see webmat readme for more
> Automatic format!

- demo/grow-height-animation.html
- demo/index.html
- demo/x-select.html
- test/iron-dropdown.html
fixes modulizer. We can't use the html import version of this because we can't use the minified polyfill in an es6 module.
> animations polyfill import to script

- test/index.html
- test/iron-dropdown.html
- test/x-scrollable-element.html
One thing that I'm worried about is that the tests still throw an error about loading lodash's `index.js` (containing `module.exports = require('./lodash');`) when you navigate to the test page itself, rather than just WCT's `generated-index.html`. I'm not sure why this happens yet.
This page works:
`http://[host]/components/@polymer/iron-dropdown/generated-index.html`
.. which contains a reference to run this page, which fails (outside of the actual tests) when you load it directly:
`http://[host]/components/@polymer/iron-dropdown/test/iron-dropdown.html`
> Fix 3.x tests.

- gen-tsd.json
https://github.com/Polymer/tools/pull/645 means we don't need this
See also https://github.com/PolymerElements/iron-dropdown/pull/165 for aborted alternative approach.
> Remove gen-tsd.json
